export const config = {
    BLANK: 0,
    WALL: {
        TOP: 2,
        LEFT: 3,
        RIGHT: 4,
        BOTTOM: 5,

        TOP_LEFT: 6,
        TOP_RIGHT: 7,
        BOTTOM_RIGHT: 8,
        BOTTOM_LEFT: 9,
        
        INNER_TOP_LEFT: 10,
        INNER_TOP_RIGHT: 11,
        INNER_BOTTOM_LEFT: 12,
        INNER_BOTTOM_RIGHT: 13
    },
    FLOOR: 1,
		JEWELRY_COLLISION: {
			STATUE_TOP: 100,
			STATUE_BOTTOM: 101,
				
			STATUE_DRAGON_TOP_LEFT: 102,
			STATUE_DRAGON_TOP_RIGHT: 103,
			STATUE_DRAGON_BOTTOM_LEFT: 104,
			STATUE_DRAGON_BOTTOM_RIGHT: 105,
				
			BIG_BONES_TOP_LEFT: 106,
			BIG_BONES_TOP_RIGHT: 107,
			BIG_BONES_BOTTOM_LEFT: 108,
			BIG_BONES_BOTTOM_RIGHT: 109,

			STONE: 110,
		},		
		JEWELRY_NONCOLLISION: {
			BONES: 111,
		  CRACK: 112,
			SMALL_STONE: 113
		},
	  INTERACTIVE_OBJECT: {
		  POTION: 114,
		  SCROLLS: 115,
		  GOLD_HEAP: 116,
		  GOLD_INGOTS: 117
	}
}

export const digitToType = {
    0: 'BLANK',
    1: 'FLOOR',
    2: 'TOP',
    3: 'LEFT',
    4: 'RIGHT',
    5: 'BOTTOM',
    6: 'TOP_LEFT',
    7: 'TOP_RIGHT',
    8: 'BOTTOM_RIGHT',
    9: 'BOTTOM_LEFT',
    10: 'INNER_TOP_LEFT',
    11: 'INNER_TOP_RIGHT',
    12: 'INNER_BOTTOM_LEFT',
    13: 'INNER_BOTTOM_RIGHT',
		100: 'STATUE_TOP',
		101: 'STATUE_BOTTOM',
		102: 'STATUE_DRAGON_TOP_LEFT',
		103: 'STATUE_DRAGON_TOP_RIGHT',
		104: 'STATUE_DRAGON_BOTTOM_LEFT',
		105: 'STATUE_DRAGON_BOTTOM_RIGHT',
		106: 'BIG_BONES_TOP_LEFT',
		107: 'BIG_BONES_TOP_RIGHT',
		108: 'BIG_BONES_BOTTOM_LEFT',
		109: 'BIG_BONES_BOTTOM_RIGHT',
		110: 'STONE',
		111: 'BONES',
		112: 'CRACK',
		113: 'SMALL_STONE',
		114: 'POTION',
		115: 'SCROLLS',
		116: 'GOLD_HEAP',
		117: 'GOLD_INGOTS' 
}